#!/bin/bash

# VARIABLES
HOST_PREFIX="mycluster"
NETWORK_NAME=$HOST_PREFIX

N=${1:-2}

#####################################
# Prepare ssh root access

# MASTER

HADOOP_MASTER="$HOST_PREFIX-master"
SSH_USER="root"
DOCKER_CONTAINER=$HADOOP_MASTER
DOCKER_CONTAINER_NETWORK=$NETWORK_NAME

echo "HADOOP_MASTER : $HADOOP_MASTER"
echo "SSH_USER : $SSH_USER"
echo "DOCKER_CONTAINER : $DOCKER_CONTAINER"
echo "DOCKER_CONTAINER_NETWORK: $DOCKER_CONTAINER_NETWORK"

sh prepare_ssh_root.sh "$SSH_USER" "$DOCKER_CONTAINER" "$DOCKER_CONTAINER_NETWORK"


# SLAVES 
i=1
while [ $i -le $N ]
do
	HADOOP_SLAVE="$HOST_PREFIX-slave-$i"
	SSH_USER="root"
    DOCKER_CONTAINER=$HADOOP_SLAVE
    DOCKER_CONTAINER_NETWORK=$NETWORK_NAME

    echo "HADOOP_SLAVE : $HADOOP_SLAVE"
    echo "SSH_USER : $SSH_USER"
    echo "DOCKER_CONTAINER : $DOCKER_CONTAINER"
    echo "DOCKER_CONTAINER_NETWORK: $DOCKER_CONTAINER_NETWORK"

    sh prepare_ssh_root.sh "$SSH_USER" "$DOCKER_CONTAINER" "$DOCKER_CONTAINER_NETWORK"
	i=$(( $i + 1 ))
done
